$LAB
.script('js/lib/Detector.js').wait()
.script('js/lib/three.js/r69/three.min.js').wait()
.script('js/lib/TrackballControls.js')
.script('js/three_ui.js')
.script('js/rest.js')
.script('js/shared.js')
.script('js/material.js')
.script('js/shapes.js')
.script('js/scene.js')
.script('js/controller.js')
.script('js/measure.js')
.script('js/animation.js')
.script('js/t-1000.js')
.script('js/collapsor.js')
.script('js/celestiary.js')
.script('js/init.js').wait(function() {
  init();
});
