name: GitHub Pages build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: gh-pages
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/build
        with:
          base-path: /${{ github.event.repository.name }}/

      - name: Deploy main to gh-pages root
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true
          clean-exclude: |
            pr-preview
          commit-message: "deploy main from ${{ github.sha }}"
